CREATE TABLE "keys" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "clave" varchar(255) NOT NULL UNIQUE,
  "key" varchar(255) NOT NULL UNIQUE,
  "usuario_id" INT NOT NULL,
  "pasarela_id" INT NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  FOREIGN KEY("usuario_id") REFERENCES "usuarios"("id") ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY("pasarela_id") REFERENCES "pasarelas"("id") ON UPDATE CASCADE ON DELETE CASCADE
);